# Generated by Django 3.2.16 on 2022-11-03 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
