# Generated by Django 3.2.15 on 2022-11-02 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0001_initial'),
        ('Product', '0003_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Payment.payment_method'),
        ),
        migrations.DeleteModel(
            name='Payment_method',
        ),
    ]
