# Generated by Django 3.2.15 on 2022-11-02 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('City', '0001_initial'),
        ('Product', '0004_auto_20221102_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='City.city'),
        ),
    ]
