# Generated by Django 3.2.15 on 2022-11-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_alter_order_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='information',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
