# Generated by Django 3.2.15 on 2022-11-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('display_name', models.CharField(max_length=10)),
                ('info', models.CharField(max_length=30)),
            ],
        ),
    ]
